### ISSUE TITLE
AWS Support

### ISSUE THREAD

**Issue by jheld** [jaddison/django-simple-elasticsearch#11]
Is there current support for connecting to an AWS elasticsearch node, instead of localhost/regular IP driven? This has the requirement of needing to send over access & token information. Amazon has a boto library that may help. 

If not, how hard/long do you think it would be to allow that support? I imagine you wouldn't be doing it yourself in a short time span, if ever.

**Comment by jaddison** [comment]
Using just the regular Python Elasticsearch module, hope would you connect?

**Comment by jheld** [comment]
Tell that to the django-haystack developers! I'll take a look when I have time to dedicate to that specifically. Will be within a couple weeks most likely.

Thanks for the quick response.

**Comment by jaddison** [comment]
Quick answer: based on https://elasticsearch-py.readthedocs.org/en/master/#running-with-aws-elasticsearch-service, it looks possible given the current connection options in `simple_elasticsearch`. In your `settings.py`, simply override `ELASTICSEARCH_CONNECTION_PARAMS` (you'll have to look in the code for it - sorry, I need to update the docs), like so (this is untested):

```
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

host = 'YOURHOST.us-east-1.es.amazonaws.com'
awsauth = AWS4Auth(YOUR_ACCESS_KEY, YOUR_SECRET_KEY, REGION, 'es')

ELASTICSEARCH_CONNECTION_PARAMS =  dict(
    hosts=[{'host': host, 'port': 443}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection
)
```

I think that **should** work.  **PLEASE NOTE** that I'm currently revamping this project in a backwards-incompatible fashion to support Django >= 1.8, but the above remains the same. See branch https://github.com/jaddison/django-simple-elasticsearch/tree/es2.0 and the release notes here: https://github.com/jaddison/django-simple-elasticsearch/blob/es2.0/HISTORY.rst

Please let me know if the above works as needed.
