### ISSUE TITLE
Consider using Box for Results

### ISSUE THREAD

**Issue by jaddison** [jaddison/django-simple-elasticsearch#17]
`Result` can be made more intuitive and user-friendly by using something like https://github.com/cdgriffith/Box to 'wrap' the result data dict.

(Perhaps this could be useful for `Response` as well?)

**Comment by avelis** [comment]
@jaddison As an alternative we used Python [FlatDict](https://github.com/gmr/flatdict) to achieve a similar result.

However, nested dictionary lookups are different with FlatDict.

Python Box makes lookups at like object attributes:
```python
results.hits.hits
```

FlatDict continues with dictionary syntax lookups:
```python
results['hits.hits']
```

I chose FlatDict out of personal ease of use and preference. In my view it reminded me that the results were still a dictionary and not some other complex object. However, your preference may and architecture choice may differ.
