### ISSUE TITLE
Fields update when model field is changed on post_save but foreign key relationships in Elasticsearch don't update

### ISSUE THREAD

**Issue by Khbero00** [jaddison/django-simple-elasticsearch#21]
So I've set up the Elasticsearchmixin, and it works well. However, I notice that when I update a field within a model. That field is updated in Elasticsearch due to the post_save but all the other models that have foreign key relationships to that model field don't update within Elasticsearch. Is there a way that when you change the username of a specific user, it not only updates that user, but the username within every model that user is tied to?

**Comment by jaddison** [comment]
@Khbero00, you'd need to use Django's `post_save` signal.

**Comment by jaddison** [comment]
Closing due to lack of response.
